// <auto-generated />
using System;
using DbRepository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DbRepository.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Entities.GuidebookTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("GuidebookTypes");
                });

            modelBuilder.Entity("Entities.ObjectInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<int?>("GuidebookTypeId");

                    b.Property<string>("Name")
                        .HasMaxLength(512);

                    b.Property<string>("Uniqcode")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("GuidebookTypeId");

                    b.ToTable("ObjectsInventory");
                });

            modelBuilder.Entity("Entities.ObjectInventory", b =>
                {
                    b.HasOne("Entities.GuidebookTypes", "GuidebookType")
                        .WithMany()
                        .HasForeignKey("GuidebookTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
